# Silence UI Service
apiVersion: v1
kind: Service
metadata:
  name: silence-ui
  namespace: alert-history
  labels:
    app: silence-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: silence-ui
