{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alert-history.postgresql.secretName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "alert-history.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  password: {{ .Values.postgresql.password | b64enc }}
{{- end }}
